<?php
// scratch/merge_final_fixes.php

$projectRoot = __DIR__ . '/..';
$arJsonPath = $projectRoot . '/messages/ar.json';

// Load existing translations
$arTranslations = [];
if (file_exists($arJsonPath)) {
    $arTranslations = json_decode(file_get_contents($arJsonPath), true) ?: [];
}

// Final fixes translations mapping
$fixesTranslations = [
    "A safe space to heal," => "مساحة آمنة للشفاء،",
    "grow, and feel" => "والنمو، والشعور",
    "heard." => "بأنك مسموع.",
    "Anonymous therapy with real support," => "علاج سري بدعم حقيقي،",
    "whenever you need it." => "في أي وقت تحتاجه.",
    "Start Your Journey" => "ابدأ رحلتك",
    "How It Works" => "كيف يعمل",
    "Private" => "خاص",
    "Secure" => "آمن",
    "100% Anonymous" => "سري ١٠٠٪",
    "Your privacy is our" => "خصوصيتك هي",
    "highest priority." => "أولويتنا القصوى.",
    "Professional Support" => "دعم احترافي",
    "Licensed therapists" => "معالجون مرخصون",
    "who truly listen." => "يستمعون إليك حقاً.",
    "Flexible & Convenient" => "مرن وملائم",
    "Talk whenever and" => "تحدث في أي وقت",
    "wherever you feel safe." => "وفي أي مكان تشعر فيه بالأمان.",
    "For Everyone" => "للجميع",
    "Support for any challenge" => "الدعم لأي تحدٍ",
    "you're facing." => "تواجهه.",
    "ABOUT US" => "عنا",
    "Therapy, on your terms." => "علاج بشروطك الخاصة.",
    "Learn More About Us" => "اكتشف المزيد عنا",
    "You're in control." => "أنت في موقع السيطرة.",
    "Choose your therapist" => "اختر معالجك الخاص",
    "Chat, call, or message" => "دردش، اتصل، أو أرسل رسالة",
    "Cancel anytime" => "إلغاء في أي وقت",
    "HOW IT WORKS" => "كيف يعمل",
    "Simple. Private. Effective." => "بسيط. خاص. فعال.",
    "You're not alone" => "لست وحدك",
    "Mental Health Support FAQ" => "الأسئلة الشائعة حول دعم الصحة النفسية",
    "Frequently Asked Questions" => "الأسئلة الشائعة",
    "Find answers to common questions about our therapy platform, privacy policies, and how to get started on your mental health journey." => "ابحث عن إجابات للأسئلة الشائعة حول منصتنا العلاجية، سياسات الخصوصية، وكيفية البدء في رحلة صحتك النفسية.",
    "How does anonymous therapy work?" => "كيف يعمل العلاج بهوية مجهولة وسرية؟",
    "Your privacy is our absolute priority. When you sign up, you only need to provide an email (which can be a dedicated anonymous address) and create a password. We do not require your real name, location, or any identifying documents. During sessions, you can choose text-only chat, audio-only calls, or video calls with the camera turned off. All your data and session logs are strictly confidential and encrypted." => "خصوصيتك هي أولويتنا المطلقة. عند التسجيل، تحتاج فقط إلى تقديم بريد إلكتروني (والذي يمكن أن يكون عنواناً مجهولاً مخصصاً) وإنشاء كلمة مرور. نحن لا نطلب اسمك الحقيقي أو موقعك أو أي وثائق هوية. خلال الجلسات، يمكنك اختيار الدردشة النصية فقط أو المكالمات الصوتية فقط أو مكالمات الفيديو مع إيقاف تشغيل الكاميرا. جميع بياناتك وسجلات الجلسات سرية للغاية ومشفرة.",
    "Are the therapists certified professionals?" => "هل المعالجون مهنيون معتمدون؟",
    "Yes. Every therapist on the Safe Haven platform undergoes a rigorous vetting process. We verify their credentials, licenses, and clinical experience before they are allowed to host sessions. Our team consists of licensed psychologists, clinical social workers, and certified counselors with diverse specialties ranging from anxiety and depression to trauma and relationship counseling." => "نعم. يخضع كل معالج على منصة الملاذ الآمن لعملية تدقيق صارمة. نحن نتحقق من أوراق اعتمادهم وتراخيصهم وخبرتهم السريرية قبل السماح لهم باستضافة الجلسات. يتكون فريقنا من أخصائيين نفسيين مرخصين، وأخصائيين اجتماعيين سريريين، ومستشارين معتمدين ذوي تخصصات متنوعة تتراوح من القلق والاكتئاب إلى الصدمات والاستشارات الزوجية والعلاقات.",
    "What is the cancellation and rescheduling policy?" => "ما هي سياسة الإلغاء وإعادة الجدولة؟",
    "You can cancel or reschedule a session directly from your dashboard. If a therapist needs to cancel a session, you will receive a formal notification explaining the reason, and your account will be immediately refunded. For rescheduling, we offer a flexible system that allows both clients and therapists to propose alternative times without losing the reserved slot until both parties agree." => "يمكنك إلغاء أو إعادة جدولة الجلسة مباشرة من لوحة التحكم الخاصة بك. إذا كان المعالج بحاجة إلى إلغاء الجلسة، فستتلقى إشعاراً رسمياً يشرح السبب، وسيتم استرداد الأموال إلى حسابك فوراً. بالنسبة لإعادة الجدولة، نحن نقدم نظاماً مرناً يتيح لكل من العملاء والمعالجين اقتراح أوقات بديلة دون فقدان الفترة المحجوزة حتى يوافق الطرفان.",
    "Is there financial support available?" => "هل هناك دعم مالي متاح؟",
    "We believe mental healthcare should be accessible to everyone. Safe Haven offers a free Group Therapy Hub and Community Q&A section led by volunteers and professionals. For one-on-one sessions, we occasionally provide subsidized rates based on financial need. Please contact our support team through the Contact Hub if you require financial assistance options." => "نحن نؤمن بأن الرعاية الصحية النفسية يجب أن تكون متاحة للجميع. يقدم الملاذ الآمن مركزاً مجانياً للعلاج الجماعي وقسماً مجتمعياً للأسئلة والأجوبة يديره متطوعون ومتخصصون. بالنسبة للجلسات الفردية، نقدم أحياناً أسعاراً مدعومة بناءً على الحاجة المالية. يرجى الاتصال بفريق الدعم لدينا من خلال مركز الاتصال إذا كنت بحاجة إلى خيارات المساعدة المالية.",
    "Still have questions?" => "ما زال لديك أسئلة؟",
    "We're here to help. Reach out to our support team and we'll get back to you as soon as possible." => "نحن هنا للمساعدة. تواصل مع فريق الدعم لدينا وسنعاود الاتصال بك في أقرب وقت ممكن.",
    "Group Therapy Sessions" => "جلسات العلاج الجماعي",
    "Connect with others in a supportive environment" => "تواصل مع الآخرين في بيئة داعمة ومحفزة",
    "Moderator" => "المشرف",
    "Start Session" => "بدء الجلسة",
    "Leave Session" => "مغادرة الجلسة",
    "Connecting to chat..." => "جاري الاتصال بالدردشة...",
    "You are currently muted by the therapist." => "لقد تم كتم صوتك حالياً من قبل المعالج.",
    "Waiting for therapist to start the session..." => "بانتظار المعالج لبدء الجلسة...",
    "Chat is closed as the session has ended." => "الدردشة مغلقة نظراً لانتهاء الجلسة.",
    "Participants (" => "المشاركون (",
    "No messages yet. Say hi!" => "لا توجد رسائل بعد. قل مرحباً!",
    "Remove" => "إزالة",
    "Report" => "إبلاغ",
    "Online" => "متصل بالإنترنت",
    "Muted" => "مكتوم",
    "Community Support" => "دعم المجتمع",
    "Connect with others facing similar challenges" => "تواصل مع الآخرين الذين يواجهون تحديات مماثلة",
    "Professional Guidance" => "التوجيه المهني",
    "Led by licensed therapists who moderate discussions" => "تحت إشراف معالجين مرخصين يوجهون المناقشات",
    "Free Access" => "وصول مجاني",
    "All group sessions are completely free to join" => "جميع الجلسات الجماعية مجانية تماماً للانضمام",
    "All quiet in the rooms..." => "كل شيء هادئ في الغرف...",
    "Check back soon for new sessions scheduled by our therapists." => "يرجى مراجعة الصفحة قريباً لرؤية جلسات جديدة مجدولة من قبل معالجينا.",
    "(60 minutes)" => "(٦٠ دقيقة)",
    "Full" => "ممتلئة",
    "Free" => "مجانية",
    "Group Guidelines" => "إرشادات المجموعة",
    "To ensure a safe and supportive environment for everyone" => "لضمان بيئة آمنة وداعمة للجميع",
    "Respect Privacy" => "احترم الخصوصية",
    "What's shared in the group stays in the group. Confidentiality is crucial." => "ما يشاركه الأعضاء في المجموعة يبقى في المجموعة. السرية أمر بالغ الأهمية.",
    "Be Supportive" => "كن داعماً",
    "Listen actively and offer support without judgment." => "استمع بفاعلية وقدم الدعم دون أحكام مسبقة.",
    "Follow Moderator Guidance" => "اتبع توجيهات الميسر",
    "The therapist moderator may mute participants or remove disruptive messages." => "يجوز للمعالج الميسر كتم صوت المشاركين أو إزالة الرسائل المزعجة.",
    "Stay On Topic" => "التزم بالموضوع الأساسي",
    "Keep discussions relevant to the session's focus." => "أبقِ المناقشات ذات صلة بتركيز وموضوع الجلسة الحالية.",
    "Create New Room" => "إنشاء غرفة جديدة",
    "Group Session" => "جلسة جماعية",
    "Availability" => "التوفر",
    "Professional, anonymous therapy services to support your mental well-being journey." => "خدمات علاجية مهنية وبسرية تامة لدعم رحلة عافيتك النفسية.",
    "Quick Links" => "روابط سريعة",
    "Available 24/7" => "متاح على مدار الساعة",
    "Your privacy is our priority. All sessions are confidential." => "خصوصيتك هي أولويتنا. جميع الجلسات سرية تماماً.",
    "Language" => "اللغة",
    "EN" => "EN",
    "AR" => "AR",
    "Save Space" => "حفظ المساحة",
    "Things you can" => "أشياء يمكنك أن",
    "see" => "تراها",
    "right now" => "الآن",
    "feel" => "تشعر بها",
    "(touch)" => "(تلمسها)",
    "hear" => "تسمعها",
    "smell" => "تشمها",
    "Thing you can" => "أشياء يمكنك أن",
    "taste" => "تتذوقها",
    "New Designs" => "تصاميم جديدة",
    "My Gallery" => "معرضي الخاص",
    "Mandala" => "ماندالا",
    "Lotus" => "لوتس",
    "Geometric Star" => "نجمة هندسية",
    "Ocean Waves" => "أمواج المحيط",
    "B" => "عريض",
    "I" => "مائل",
    "U" => "تحته خط",
    "H2" => "عنوان ٢",
    "H3" => "عنوان ٣",
    "1. List" => "قائمة رقمية",
    "😊 Emoji" => "رمز تعبيري 😊",
    "Angry" => "غاضب",
    "Anxious" => "قلق",
    "Grateful" => "ممتن"
];

// Merge and save
foreach ($fixesTranslations as $key => $val) {
    $normKey = trim($key);
    $arTranslations[$normKey] = $val;
}

// Format nicely and write back to messages/ar.json
file_put_contents($arJsonPath, json_encode($arTranslations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
echo "Successfully merged " . count($fixesTranslations) . " fixes translations into ar.json.\n";
